import { ENV } from '../../../env';

export const APP_CONSTANTS = {
  DEFAULT_PORT: ENV.PORT,
  API_PREFIX: 'api',
  JWT_SECRET: ENV.JWT_SECRET,
  JWT_EXPIRES_IN: ENV.JWT_EXPIRES_IN,
  JWT_REFRESH_SECRET: ENV.JWT_REFRESH_SECRET,
  JWT_REFRESH_EXPIRES_IN: ENV.JWT_REFRESH_EXPIRES_IN,
  BCRYPT_SALT_ROUNDS: 10,
  CORS_ORIGIN: ENV.CORS_ORIGIN,
} as const;

export const DATABASE_CONSTANTS = {
  TYPE: ENV.DATABASE_TYPE,
  HOST: ENV.DATABASE_HOST,
  PORT: ENV.DATABASE_PORT,
  USERNAME: ENV.DATABASE_USERNAME,
  PASSWORD: ENV.DATABASE_PASSWORD,
  DATABASE: ENV.DATABASE_NAME,
  SYNCHRONIZE: ENV.DATABASE_SYNCHRONIZE,
  LOGGING: ENV.DATABASE_LOGGING,
  MIGRATIONS_RUN: ENV.DATABASE_MIGRATIONS_RUN,
} as const;

export const EMAIL_CONSTANTS = {
  HOST: ENV.EMAIL_HOST,
  PORT: ENV.EMAIL_PORT,
  SECURE: ENV.EMAIL_SECURE,
  USER: ENV.EMAIL_USER,
  PASSWORD: ENV.EMAIL_PASSWORD,
  FROM: ENV.EMAIL_FROM,
} as const;

export const VALIDATION_CONSTANTS = {
  WHITELIST: true,
  FORBID_NON_WHITELISTED: true,
  TRANSFORM: true,
  DISMISS_DEFAULT_MESSAGES: false,
} as const;
